name: flutter_piaui_website
description: The Website developed for community Flutter Piaui.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0

assets:
  - assets/images/
  - lib/assets/images/
  - data/

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
    - data/
